# Generated by Django 5.2.9 on 2025-12-26 07:47

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWorkstation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('category', models.CharField(choices=[('main', 'Основное'), ('aux', 'Вспомогательное'), ('meas', 'Контрольно-измерительное'), ('test', 'Испытательное'), ('other', 'Другое')], default='main', max_length=20, verbose_name='Категория оборудования')),
                ('type_name', models.CharField(max_length=255, verbose_name='Тип оборудования')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=255, verbose_name='Модель')),
                ('global_state', models.CharField(choices=[('active', 'Введено в эксплуатацию'), ('arch', 'В архиве'), ('reserve', 'Резерв'), ('decommissioned', 'Выведено из эксплуатации')], default='active', max_length=20, verbose_name='Глобальное состояние')),
                ('status', models.CharField(choices=[('prod', 'Работает'), ('problem', 'Аварийный ремонт'), ('maint', 'Техническое обслуживание'), ('setup', 'Пусконаладочные работы'), ('reserved', 'В резерве'), ('decommissioned', 'Выведено из эксплуатации')], default='prod', max_length=20, verbose_name='Текущее состояние')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Инвентарный номер')),
                ('commissioning_date', models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Гарантия до')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.TextField(blank=True, max_length=500, verbose_name='Фотография')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Обновлено')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.location', verbose_name='Локация')),
                ('responsible', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.humanresource', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'historical Оборудование',
                'verbose_name_plural': 'historical Оборудование',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('category', models.CharField(choices=[('main', 'Основное'), ('aux', 'Вспомогательное'), ('meas', 'Контрольно-измерительное'), ('test', 'Испытательное'), ('other', 'Другое')], default='main', max_length=20, verbose_name='Категория оборудования')),
                ('type_name', models.CharField(max_length=255, verbose_name='Тип оборудования')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=255, verbose_name='Модель')),
                ('global_state', models.CharField(choices=[('active', 'Введено в эксплуатацию'), ('arch', 'В архиве'), ('reserve', 'Резерв'), ('decommissioned', 'Выведено из эксплуатации')], default='active', max_length=20, verbose_name='Глобальное состояние')),
                ('status', models.CharField(choices=[('prod', 'Работает'), ('problem', 'Аварийный ремонт'), ('maint', 'Техническое обслуживание'), ('setup', 'Пусконаладочные работы'), ('reserved', 'В резерве'), ('decommissioned', 'Выведено из эксплуатации')], default='prod', max_length=20, verbose_name='Текущее состояние')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Инвентарный номер')),
                ('commissioning_date', models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Гарантия до')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, max_length=500, upload_to='workstations/%Y/%m/%d/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workstations', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workstations', to='locations.location', verbose_name='Локация')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_workstations', to='hr.humanresource', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'global_state'], name='assets_work_status_7f608d_idx'), models.Index(fields=['location', 'category'], name='assets_work_locatio_e3cb99_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('serial_number', 'manufacturer'), name='unique_serial_manufacturer')],
            },
        ),
    ]
