# Generated by Django 5.2.6 on 2025-09-21 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('category', models.CharField(choices=[('main', 'Основное'), ('aux', 'Вспомогательное'), ('meas', 'Контрольно-измерительное'), ('test', 'Испытательное'), ('other', 'Другое')], default='main', max_length=20, verbose_name='Категория оборудования')),
                ('type_name', models.CharField(max_length=255, verbose_name='Тип оборудования')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=255, verbose_name='Модель')),
                ('global_state', models.CharField(choices=[('wait', 'Ожидание ввода в эксплуатацию'), ('active', 'Введено в эксплуатацию'), ('arch', 'В архиве')], default='wait', max_length=20, verbose_name='Глобальное состояние')),
                ('status', models.CharField(choices=[('prod', 'Работает'), ('off', 'Выключено'), ('idle', 'Простой'), ('problem', 'Аварийный ремонт'), ('maint', 'Техническое обслуживание'), ('setup', 'Пусконаладочные работы')], default='off', max_length=20, verbose_name='Текущее состояние')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('serial_number', models.CharField(blank=True, max_length=255, verbose_name='Серийный номер')),
                ('commissioning_date', models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Гарантия до')),
                ('photo', models.ImageField(blank=True, upload_to='workstations/', verbose_name='Фотография')),
                ('inventory_number', models.CharField(blank=True, max_length=255, verbose_name='Инвентарный номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location', verbose_name='Локация')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.humanresource', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
    ]
