# Generated by Django 5.2.9 on 2026-01-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkstation',
            name='type_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='type_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип оборудования'),
        ),
    ]
