# Generated by Django 5.2.6 on 2025-09-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='global_state',
            field=models.CharField(choices=[('active', 'Введено в эксплуатацию'), ('arch', 'В архиве')], default='active', max_length=20, verbose_name='Глобальное состояние'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='status',
            field=models.CharField(choices=[('prod', 'Работает'), ('problem', 'Аварийный ремонт'), ('maint', 'Техническое обслуживание'), ('setup', 'Пусконаладочные работы')], default='prod', max_length=20, verbose_name='Текущее состояние'),
        ),
    ]
