# Generated by Django 5.2.9 on 2025-12-24 10:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_workstation_global_state_and_more'),
        ('hr', '0002_humanresource_manager'),
        ('locations', '0002_remove_location_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWorkstation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('category', models.CharField(choices=[('main', 'Основное'), ('aux', 'Вспомогательное'), ('meas', 'Контрольно-измерительное'), ('test', 'Испытательное'), ('other', 'Другое')], default='main', max_length=20, verbose_name='Категория оборудования')),
                ('type_name', models.CharField(max_length=255, verbose_name='Тип оборудования')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=255, verbose_name='Модель')),
                ('global_state', models.CharField(choices=[('active', 'Введено в эксплуатацию'), ('arch', 'В архиве')], default='active', max_length=20, verbose_name='Глобальное состояние')),
                ('status', models.CharField(choices=[('prod', 'Работает'), ('problem', 'Аварийный ремонт'), ('maint', 'Техническое обслуживание'), ('setup', 'Пусконаладочные работы')], default='prod', max_length=20, verbose_name='Текущее состояние')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('serial_number', models.CharField(blank=True, max_length=255, verbose_name='Серийный номер')),
                ('commissioning_date', models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Гарантия до')),
                ('photo', models.TextField(blank=True, max_length=100, verbose_name='Фотография')),
                ('inventory_number', models.CharField(blank=True, max_length=255, verbose_name='Инвентарный номер')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Создано')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.location', verbose_name='Локация')),
                ('responsible', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.humanresource', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'historical Оборудование',
                'verbose_name_plural': 'historical Оборудование',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
