# Generated by Django 5.2.9 on 2025-12-26 10:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('job_title', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, help_text='Сотрудник работает в компании', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hr.humanresource', verbose_name='Начальник')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalHumanResource',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('job_title', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, help_text='Сотрудник работает в компании', verbose_name='Активен')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Обновлен')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.humanresource', verbose_name='Начальник')),
            ],
            options={
                'verbose_name': 'historical Сотрудник',
                'verbose_name_plural': 'historical Сотрудники',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='humanresource',
            index=models.Index(fields=['name'], name='hr_humanres_name_d5c835_idx'),
        ),
        migrations.AddIndex(
            model_name='humanresource',
            index=models.Index(fields=['job_title'], name='hr_humanres_job_tit_eb999a_idx'),
        ),
        migrations.AddIndex(
            model_name='humanresource',
            index=models.Index(fields=['is_active'], name='hr_humanres_is_acti_486809_idx'),
        ),
        migrations.AddIndex(
            model_name='humanresource',
            index=models.Index(fields=['manager', 'is_active'], name='hr_humanres_manager_e7ad2b_idx'),
        ),
    ]
