# Generated by Django 5.2.6 on 2025-09-18 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название склада')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('group', models.CharField(blank=True, max_length=255, verbose_name='Группа')),
                ('article', models.CharField(blank=True, max_length=255, verbose_name='Артикул')),
                ('part_number', models.CharField(blank=True, max_length=255, verbose_name='Номер детали')),
                ('uom', models.CharField(choices=[('pcs', 'шт'), ('kg', 'кг'), ('l', 'л'), ('m', 'м'), ('h', 'ч')], default='pcs', max_length=10, verbose_name='Ед. изм.')),
                ('qty_available', models.FloatField(default=0, verbose_name='Количество (свободно)')),
                ('qty_reserved', models.FloatField(default=0, verbose_name='Количество (резерв)')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
    ]
