# Generated by Django 5.2.6 on 2025-09-27 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_humanresource_manager'),
        ('inventory', '0001_initial'),
        ('locations', '0002_remove_location_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hr.humanresource', verbose_name='Ответственный'),
        ),
    ]
