# Generated by Django 5.2.9 on 2025-12-26 18:41

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('inventory', '0002_add_created_updated_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name'], 'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенклатура'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AddField(
            model_name='historicalmaterial',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalmaterial',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата обновления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='qty_available',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество (свободно)'),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='qty_reserved',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество (резерв)'),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='uom',
            field=models.CharField(choices=[('pcs', 'шт'), ('kg', 'кг'), ('l', 'л'), ('m', 'м'), ('h', 'ч'), ('set', 'комплект'), ('roll', 'рулон')], default='pcs', max_length=10, verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='qty_available',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество (свободно)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='qty_reserved',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество (резерв)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='uom',
            field=models.CharField(choices=[('pcs', 'шт'), ('kg', 'кг'), ('l', 'л'), ('m', 'м'), ('h', 'ч'), ('set', 'комплект'), ('roll', 'рулон')], default='pcs', max_length=10, verbose_name='Ед. изм.'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['name'], name='inventory_m_name_1014de_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['article'], name='inventory_m_article_a8ecf6_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['part_number'], name='inventory_m_part_nu_9255a0_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['is_active'], name='inventory_m_is_acti_cdcacf_idx'),
        ),
    ]
