# Generated by Django 5.2.9 on 2025-12-21 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_humanresource_manager'),
        ('inventory', '0002_material_vendor_warehouse_location_and_more'),
        ('locations', '0002_remove_location_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.humanresource', verbose_name='Ответственный'),
        ),
    ]
