# Generated by Django 5.2.9 on 2025-12-26 19:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('hr', '0001_initial'),
        ('inventory', '0003_alter_material_options_alter_warehouse_options_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmaterial',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalmaterial',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='material',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='material',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='historicalmaterial',
            name='min_stock_level',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальный запас'),
        ),
        migrations.AddField(
            model_name='historicalmaterial',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='material',
            name='min_stock_level',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальный запас'),
        ),
        migrations.AddField(
            model_name='material',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='uom',
            field=models.CharField(choices=[('pcs', 'шт'), ('kg', 'кг'), ('l', 'л'), ('m', 'м'), ('h', 'ч'), ('set', 'комплект'), ('roll', 'рулон'), ('box', 'коробка'), ('pal', 'паллет')], default='pcs', max_length=10, verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='material',
            name='uom',
            field=models.CharField(choices=[('pcs', 'шт'), ('kg', 'кг'), ('l', 'л'), ('m', 'м'), ('h', 'ч'), ('set', 'комплект'), ('roll', 'рулон'), ('box', 'коробка'), ('pal', 'паллет')], default='pcs', max_length=10, verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='inventory.warehouse', verbose_name='Склад'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['warehouse'], name='inventory_m_warehou_3f7910_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['group'], name='inventory_m_group_fcba50_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['name'], name='inventory_w_name_703b74_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['location'], name='inventory_w_locatio_1c9365_idx'),
        ),
    ]
