# Generated by Django 5.2.9 on 2025-12-24 10:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_historicalhumanresource'),
        ('inventory', '0003_alter_warehouse_location_alter_warehouse_responsible'),
        ('locations', '0003_historicallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMaterial',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('group', models.CharField(blank=True, max_length=255, verbose_name='Группа')),
                ('article', models.CharField(blank=True, max_length=255, verbose_name='Артикул')),
                ('part_number', models.CharField(blank=True, max_length=255, verbose_name='Номер детали')),
                ('uom', models.CharField(choices=[('pcs', 'шт'), ('kg', 'кг'), ('l', 'л'), ('m', 'м'), ('h', 'ч')], default='pcs', max_length=10, verbose_name='Ед. изм.')),
                ('qty_available', models.FloatField(default=0, verbose_name='Количество (свободно)')),
                ('qty_reserved', models.FloatField(default=0, verbose_name='Количество (резерв)')),
                ('vendor', models.CharField(blank=True, max_length=255, verbose_name='Производитель')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'historical Номенклатура',
                'verbose_name_plural': 'historical Номенклатура',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWarehouse',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название склада')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.location', verbose_name='Локация')),
                ('responsible', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.humanresource', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'historical Склад',
                'verbose_name_plural': 'historical Склады',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
