# Generated by Django 5.2.9 on 2026-01-06 02:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('inventory', '0004_remove_historicalmaterial_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmaterial',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Минимальный запас'),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='qty_available',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество (свободно)'),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='qty_reserved',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество (резерв)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Минимальный запас'),
        ),
        migrations.AlterField(
            model_name='material',
            name='qty_available',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество (свободно)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='qty_reserved',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество (резерв)'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('qty_available__gte', 0)), name='inventory_material_qty_available_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('qty_reserved__gte', 0)), name='inventory_material_qty_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('min_stock_level__gte', 0)), name='inventory_material_min_stock_non_negative'),
        ),
    ]
