# Generated by Django 5.2.9 on 2025-12-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_historicalmaterial_historicalwarehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaterial',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='Фото'),
        ),
    ]
