# Generated by Django 5.2.9 on 2026-01-11 05:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_historicalmaterial_min_stock_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmaterial',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Минимальный запас'),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='qty_available',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество (свободно)'),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='qty_reserved',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество (резерв)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Минимальный запас'),
        ),
        migrations.AlterField(
            model_name='material',
            name='qty_available',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество (свободно)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='qty_reserved',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество (резерв)'),
        ),
    ]
