# Generated by Django 5.2.9 on 2025-12-23 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_alter_workstation_global_state_and_more'),
        ('hr', '0002_humanresource_manager'),
        ('inventory', '0003_alter_warehouse_location_alter_warehouse_responsible'),
        ('locations', '0002_remove_location_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название планового обслуживания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('inspection', 'Осмотр'), ('pm', 'Техническое обслуживание'), ('repair_minor', 'Текущий ремонт'), ('repair_major', 'Капитальный ремонт'), ('emergency', 'Аварийный ремонт')], default='pm', max_length=20, verbose_name='Категория работ')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='weekly', max_length=20, verbose_name='Периодичность')),
                ('labor_plan_hours', models.FloatField(default=1.0, verbose_name='Трудоёмкость (план), ч')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('med', 'Средний'), ('high', 'Высокий')], default='med', max_length=10, verbose_name='Приоритет')),
                ('start_from', models.DateTimeField(blank=True, null=True, verbose_name='Старт планирования (дата и время)')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Следующий запуск (дата и время)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('interval_value', models.PositiveIntegerField(default=1, help_text='Например, 3 = каждые 3 единицы времени.', verbose_name='Интервал (N)')),
                ('interval_unit', models.CharField(choices=[('minute', 'Минуты'), ('day', 'Дни'), ('week', 'Недели'), ('month', 'Месяцы')], default='week', help_text='Минуты / Дни / Недели / Месяцы', max_length=10, verbose_name='Единица интервала')),
                ('first_run_date', models.DateField(blank=True, null=True, verbose_name='Дата первого обслуживания')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, help_text='0=Пн … 6=Вс', null=True, verbose_name='День недели')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1–31', null=True, verbose_name='День месяца')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location', verbose_name='Локация')),
                ('responsible_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.humanresource', verbose_name='Ответственный по умолчанию')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.workstation', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Плановое обслуживание',
                'verbose_name_plural': 'Плановые обслуживания',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('done', 'Выполнено'), ('failed', 'Не выполнено'), ('canceled', 'Отмена')], default='new', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('inspection', 'Осмотр'), ('pm', 'Техническое обслуживание'), ('repair_minor', 'Текущий ремонт'), ('repair_major', 'Капитальный ремонт'), ('emergency', 'Аварийный ремонт')], default='pm', max_length=20, verbose_name='Категория работ')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала работ')),
                ('date_finish', models.DateField(blank=True, null=True, verbose_name='Дата окончания работ')),
                ('labor_plan_hours', models.FloatField(default=0, verbose_name='Трудоёмкость (план), ч')),
                ('labor_fact_hours', models.FloatField(default=0, verbose_name='Трудоёмкость (факт), ч')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('med', 'Средний'), ('high', 'Высокий')], default='med', max_length=10, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('createrd_from_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='maintenance.plannedorder', verbose_name='Плановое обслуживание')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='Локация')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.humanresource', verbose_name='Ответственный')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.workstation', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Рабочая задача',
                'verbose_name_plural': 'Рабочие задачи',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='workorders/', verbose_name='Файл')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='maintenance.workorder', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Файл задачи',
                'verbose_name_plural': 'Файлы задач',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_planned', models.FloatField(default=0, verbose_name='Запланировано')),
                ('qty_used', models.FloatField(default=0, verbose_name='Использовано')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material', verbose_name='Материал')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='maintenance.workorder', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Материал задачи',
                'verbose_name_plural': 'Материалы задач',
                'unique_together': {('work_order', 'material')},
            },
        ),
    ]
