# Generated by Django 5.2.6 on 2025-09-18 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('hr', '0001_initial'),
        ('inventory', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('done', 'Выполнено'), ('failed', 'Не выполнено'), ('canceled', 'Отмена')], default='new', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('inspection', 'Осмотр'), ('pm', 'Техническое обслуживание'), ('repair_minor', 'Текущий ремонт'), ('repair_major', 'Капитальный ремонт'), ('emergency', 'Аварийный ремонт')], default='pm', max_length=20, verbose_name='Категория работ')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала работ')),
                ('date_finish', models.DateField(blank=True, null=True, verbose_name='Дата окончания работ')),
                ('files', models.FileField(blank=True, upload_to='workorders/', verbose_name='Файлы')),
                ('labor_plan_hours', models.FloatField(default=0, verbose_name='Трудоёмкость (план), ч')),
                ('labor_fact_hours', models.FloatField(default=0, verbose_name='Трудоёмкость (факт), ч')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('med', 'Средний'), ('high', 'Высокий')], default='med', max_length=10, verbose_name='Приоритет')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='Локация')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.humanresource', verbose_name='Ответственный')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.workstation', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Рабочая задача',
                'verbose_name_plural': 'Рабочие задачи',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_planned', models.FloatField(default=0, verbose_name='Запланировано')),
                ('qty_used', models.FloatField(default=0, verbose_name='Использовано')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material', verbose_name='Материал')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='maintenance.workorder', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Материал задачи',
                'verbose_name_plural': 'Материалы задач',
                'unique_together': {('work_order', 'material')},
            },
        ),
    ]
