# Generated by Django 5.2.8 on 2025-12-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedorder',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1–31', null=True, verbose_name='День месяца'),
        ),
        migrations.AddField(
            model_name='plannedorder',
            name='first_run_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата первого обслуживания'),
        ),
        migrations.AddField(
            model_name='plannedorder',
            name='weekday',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0=Пн … 6=Вс', null=True, verbose_name='День недели'),
        ),
    ]
