# Generated by Django 5.2.9 on 2026-01-06 02:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_historicalmaterial_created_at_and_more'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkordermaterial',
            name='qty_planned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Запланировано'),
        ),
        migrations.AlterField(
            model_name='historicalworkordermaterial',
            name='qty_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Использовано'),
        ),
        migrations.AlterField(
            model_name='workordermaterial',
            name='qty_planned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Запланировано'),
        ),
        migrations.AlterField(
            model_name='workordermaterial',
            name='qty_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Использовано'),
        ),
        migrations.AddConstraint(
            model_name='workordermaterial',
            constraint=models.CheckConstraint(condition=models.Q(('qty_planned__gte', 0)), name='maintenance_wom_qty_planned_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='workordermaterial',
            constraint=models.CheckConstraint(condition=models.Q(('qty_used__gte', 0)), name='maintenance_wom_qty_used_non_negative'),
        ),
    ]
