# Generated by Django 5.2.6 on 2025-09-18 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('hr', '0001_initial'),
        ('locations', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название планового обслуживания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('inspection', 'Осмотр'), ('pm', 'Техническое обслуживание'), ('repair_minor', 'Текущий ремонт'), ('repair_major', 'Капитальный ремонт'), ('emergency', 'Аварийный ремонт')], default='pm', max_length=20, verbose_name='Категория работ')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='weekly', max_length=20, verbose_name='Периодичность')),
                ('labor_plan_hours', models.FloatField(default=1.0, verbose_name='Трудоёмкость (план), ч')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('med', 'Средний'), ('high', 'Высокий')], default='med', max_length=10, verbose_name='Приоритет')),
                ('start_from', models.DateField(blank=True, null=True, verbose_name='Старт планирования')),
                ('next_run', models.DateField(blank=True, null=True, verbose_name='Следующий запуск')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location', verbose_name='Локация')),
                ('responsible_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.humanresource', verbose_name='Ответственный по умолчанию')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.workstation', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Плановое обслуживание',
                'verbose_name_plural': 'Плановые обслуживания',
            },
        ),
    ]
