# Generated by Django 5.2.8 on 2025-12-20 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_plannedorder_day_of_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
    ]
