# Generated by Django 5.2.9 on 2025-12-23 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_create_workorderfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorderfile',
            options={'verbose_name': 'Файл задачи', 'verbose_name_plural': 'Файлы задач'},
        ),
        migrations.AlterField(
            model_name='workorderfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='workorders/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='workorderfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workorderfile',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='maintenance.workorder', verbose_name='Задача'),
        ),
    ]
