# Generated by Django 5.2.9 on 2026-01-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_historicalworkordermaterial_qty_planned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkorder',
            name='labor_fact_hours',
            field=models.FloatField(blank=True, default=0, verbose_name='Трудоёмкость (факт), ч'),
        ),
        migrations.AlterField(
            model_name='historicalworkorder',
            name='labor_plan_hours',
            field=models.FloatField(blank=True, default=0, verbose_name='Трудоёмкость (план), ч'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='labor_fact_hours',
            field=models.FloatField(blank=True, default=0, verbose_name='Трудоёмкость (факт), ч'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='labor_plan_hours',
            field=models.FloatField(blank=True, default=0, verbose_name='Трудоёмкость (план), ч'),
        ),
    ]
