# Generated by Django 5.2.9 on 2025-12-23 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_workorderfile_options_alter_workorderfile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderfile',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='maintenance.workorder', verbose_name='Задача'),
        ),
    ]
