# Generated by Django 5.2.9 on 2025-12-22 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_workorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='createrd_from_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='maintenance.plannedorder', verbose_name='Плановое обслуживание'),
        ),
    ]
