# Generated by Django 5.2.9 on 2025-12-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_file_alter_workorderfile_work_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkOrderFile',
        ),
    ]
