# Generated by Django 5.2.9 on 2025-12-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_historicalfile_historicalplannedorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkorder',
            old_name='createrd_from_plan',
            new_name='created_from_plan',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='createrd_from_plan',
            new_name='created_from_plan',
        ),
        migrations.AlterField(
            model_name='historicalplannedorder',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='weekly', help_text='Для справки, основная логика — через interval_value/unit', max_length=20, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='weekly', help_text='Для справки, основная логика — через interval_value/unit', max_length=20, verbose_name='Периодичность'),
        ),
    ]
